/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpaceCup.Forms;

import SpaceCup.Business.Filter.Message;
import SpaceCup.Business.Repositories.GrupoRepository;
import SpaceCup.Business.Repositories.ProjetoRepository;
import SpaceCup.Entity.Entities.Grupo;
import SpaceCup.Entity.Entities.Projeto;
import java.util.ArrayList;


/**
 *
 * @author Bruno
 */
public class GrupoForm extends javax.swing.JFrame {

    
    public GrupoForm() {
        initComponents();
        btneditar.setEnabled(false);
        btnexcluir.setEnabled(false);
        
        this.cbprojeto.removeAllItems();
        ProjetoRepository projetoRepository = new ProjetoRepository();
        ArrayList<Projeto>cbprojeto = new ArrayList(); 
        //Aqui precisamos de um array com todos os projetos
        cbprojeto = projetoRepository.GetAll();
        for (Projeto proj: cbprojeto) {
            cbprojeto.add(proj.getIdProjeto(), proj);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        txtnomegrupo = new javax.swing.JTextField();
        cbprojeto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Controle de Grupos");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Projeto:");

        cbprojeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbprojeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbprojetoActionPerformed(evt);
            }
        });

        jLabel2.setText("Grupo:");

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtnomegrupo)
                    .addComponent(cbprojeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(btnsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsair)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar)
                    .addComponent(btneditar)
                    .addComponent(btnsair)
                    .addComponent(btnexcluir)
                    .addComponent(btnbuscar))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbprojetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbprojetoActionPerformed
        
        
    }//GEN-LAST:event_cbprojetoActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        GrupoRepository gruporepository = new GrupoRepository();
      Message msg = new Message();
      String NomeGrupo = "";
      int IdProjeto=0;
      if(txtnomegrupo.getText().isEmpty()){
          msg.ErrorMessage("Preencha um nome para o grupo");
      }else{
      NomeGrupo = txtnomegrupo.getText();
      IdProjeto = cbprojeto.getSelectedIndex();
      }
      Grupo grupo = new Grupo(0, NomeGrupo, IdProjeto);
        gruporepository.Delete(grupo);
      msg.SucessMessage("Grupo excluido com sucesso");
      
      limparcampos();
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
      GrupoRepository gruporepository = new GrupoRepository();
      Message msg = new Message();
      String NomeGrupo = "";
      int IdProjeto=0;
             
      if(txtnomegrupo.getText().isEmpty()){
          msg.ErrorMessage("Preencha um nome para o grupo");
      }else{
      NomeGrupo = txtnomegrupo.getText();
      IdProjeto = cbprojeto.getSelectedIndex();
      }
      Grupo grupo = new Grupo(0, NomeGrupo, IdProjeto);
        gruporepository.Insert(grupo);
      msg.SucessMessage("Grupo inserido com sucesso");
      
      limparcampos();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
      GrupoRepository gruporepository = new GrupoRepository();
      Message msg = new Message();
      String NomeGrupo = "";
      int IdProjeto=0;
             
      if(txtnomegrupo.getText().isEmpty()){
          msg.ErrorMessage("Preencha um nome para o grupo");
      }else{
      NomeGrupo = txtnomegrupo.getText();
      IdProjeto = cbprojeto.getSelectedIndex();
      }
      Grupo grupo = new Grupo(0, NomeGrupo, IdProjeto);
        gruporepository.Update(grupo);
      msg.SucessMessage("Grupo alterado com sucesso");
      limparcampos();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        GrupoRepository gruporepository = new GrupoRepository();
      Message msg = new Message();
      String NomeGrupo = "";
      int IdProjeto=0;
     
     if(txtnomegrupo.getText().isEmpty()){
          NomeGrupo = "";
      }else{
      NomeGrupo = txtnomegrupo.getText();
      IdProjeto = cbprojeto.getSelectedIndex();
      }
      //Grupo grupo = new Grupo(0, NomeGrupo, IdProjeto);
      
      Grupo retorno = gruporepository.GetGrupo(0, NomeGrupo, IdProjeto);
      if(retorno == null){
          msg.ErrorMessage("Grupo não encontrado");
          limparcampos();
      }
      else{
          btneditar.setEnabled(true);
          btnexcluir.setEnabled(true);
          txtnomegrupo.setText(retorno.getNomeGrupo());
          cbprojeto.setSelectedIndex(retorno.getIdProjeto());
      }
      
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
         dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnsair;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> cbprojeto;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtnomegrupo;
    // End of variables declaration//GEN-END:variables

    private void limparcampos() {
        btneditar.setEnabled(false);
        btnexcluir.setEnabled(false);
        txtnomegrupo.setText("");
        cbprojeto.setSelectedIndex(0);
    }
}
